;             
CREATE USER IF NOT EXISTS "ROOT" SALT 'd8b069a5be914d9d' HASH '4950d42a020f1fe5774fb8d7e5a7ecaca62ab3fc5d4698227c4b98f1411b0581' ADMIN;       
DROP TABLE IF EXISTS "PUBLIC"."ADDRESS" CASCADE;              
DROP TABLE IF EXISTS "PUBLIC"."APP_ORDER" CASCADE;            
DROP TABLE IF EXISTS "PUBLIC"."APP_USERS" CASCADE;            
DROP TABLE IF EXISTS "PUBLIC"."CART" CASCADE; 
DROP TABLE IF EXISTS "PUBLIC"."CART_PRODUCT" CASCADE;         
DROP TABLE IF EXISTS "PUBLIC"."CATEGORY" CASCADE;             
DROP TABLE IF EXISTS "PUBLIC"."COMPANY" CASCADE;              
DROP TABLE IF EXISTS "PUBLIC"."FILE_STORE" CASCADE;           
DROP TABLE IF EXISTS "PUBLIC"."GEO" CASCADE;  
DROP TABLE IF EXISTS "PUBLIC"."ORDER_PRODUCT" CASCADE;        
DROP TABLE IF EXISTS "PUBLIC"."PRODUCT" CASCADE;              
DROP TABLE IF EXISTS "PUBLIC"."PRODUCT_ATTRIBUTE" CASCADE;    
DROP TABLE IF EXISTS "PUBLIC"."PRODUCT_PHOTO" CASCADE;        
DROP TABLE IF EXISTS "PUBLIC"."ROLE" CASCADE; 
DROP TABLE IF EXISTS "PUBLIC"."USER_ROLE" CASCADE;            
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E1300118_96B2_4EC4_BEF3_B80E20CDDCBD" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_73AB6AAD_7CDC_46FB_B2CD_651335C72558" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_4D0F0B57_AAEA_4D7A_9C50_D271CEB673C9" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D2BA9875_601F_4AC6_BBDC_BB67671D92E1" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_77C34588_B922_499C_ACDC_1D461D9985DA" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F2B87DB0_606B_4D40_B735_BF4719D02ADC" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_64FBE65A_2386_46DD_BB69_801D3B1DFBD2" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_35DD1292_D21E_4FD3_80E5_FC644811FB4B" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_850E4BB3_4F5D_4DB4_9D86_B749061EF912" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B50F1CA9_92A9_4C26_B65C_6BDB90659990" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F23B705D_2C1E_4F03_8257_C8F3576482D8" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_04C36883_86A4_4FB9_8D10_22974F015F5C" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_218B2E7D_4BBF_46E3_B380_38D9B76BCEDF" START WITH 4 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_651F689F_E715_4FA5_B53C_E0650249EE23" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."ADDRESS"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_35DD1292_D21E_4FD3_80E5_FC644811FB4B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_35DD1292_D21E_4FD3_80E5_FC644811FB4B",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "CREATED_BY" BIGINT,
    "UPDATED_BY" BIGINT,
    "CITY" VARCHAR(255),
    "STREET" VARCHAR(255),
    "SUITE" VARCHAR(255),
    "ZIPCODE" VARCHAR(255),
    "GEO_ID" BIGINT
);     
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADDRESS; 
CREATE CACHED TABLE "PUBLIC"."APP_ORDER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_77C34588_B922_499C_ACDC_1D461D9985DA" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_77C34588_B922_499C_ACDC_1D461D9985DA",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "ORDER_DATE" TIMESTAMP NOT NULL,
    "ORDER_NUM" VARCHAR(50),
    "ORDER_STATUS" VARCHAR(50),
    "USER_ID" BIGINT
);               
ALTER TABLE "PUBLIC"."APP_ORDER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APP_ORDER;               
CREATE CACHED TABLE "PUBLIC"."APP_USERS"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_E1300118_96B2_4EC4_BEF3_B80E20CDDCBD" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E1300118_96B2_4EC4_BEF3_B80E20CDDCBD",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "VERIFICATION_CODE" VARCHAR(255),
    "ACCOUNT_VERIFIED" BOOLEAN,
    "ACTIVE" BOOLEAN,
    "EMAIL" VARCHAR(40),
    "FIRST_NAME" VARCHAR(40),
    "LAST_NAME" VARCHAR(40),
    "PASSWORD" VARCHAR(100),
    "PHONE" VARCHAR(255),
    "USERNAME" VARCHAR(15),
    "WEBSITE" VARCHAR(255),
    "ADDRESS_ID" BIGINT,
    "COMPANY_ID" BIGINT
);              
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4A" PRIMARY KEY("ID");   
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.APP_USERS;               
INSERT INTO "PUBLIC"."APP_USERS" VALUES
(1, TIMESTAMP '2022-10-08 22:10:35.337275', TIMESTAMP '2022-10-08 22:10:35.337275', 'aejmjeamuacc.eaiamlp.@g.6', TRUE, TRUE, 'mgajapure6@gmail.com', 'Super', 'Admin', '$2a$10$bXp7TKqb5/qbNAjWD4q6XOz/G0HoYt/xENlLgkwkWnwQGh2eGCadG', NULL, 'admin', NULL, NULL, NULL);             
CREATE CACHED TABLE "PUBLIC"."CART"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B50F1CA9_92A9_4C26_B65C_6BDB90659990" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B50F1CA9_92A9_4C26_B65C_6BDB90659990",
    "USER_ID" BIGINT
);     
ALTER TABLE "PUBLIC"."CART" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CART;    
CREATE CACHED TABLE "PUBLIC"."CART_PRODUCT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_04C36883_86A4_4FB9_8D10_22974F015F5C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_04C36883_86A4_4FB9_8D10_22974F015F5C",
    "PRODUCT_ID" BIGINT,
    "PRODUCT_QUANTITY" DOUBLE,
    "CART_ID" BIGINT
);   
ALTER TABLE "PUBLIC"."CART_PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CART_PRODUCT;            
CREATE CACHED TABLE "PUBLIC"."CATEGORY"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_4D0F0B57_AAEA_4D7A_9C50_D271CEB673C9" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_4D0F0B57_AAEA_4D7A_9C50_D271CEB673C9",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "NAME" VARCHAR(255),
    "USER_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;
CREATE CACHED TABLE "PUBLIC"."COMPANY"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_64FBE65A_2386_46DD_BB69_801D3B1DFBD2" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_64FBE65A_2386_46DD_BB69_801D3B1DFBD2",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "CREATED_BY" BIGINT,
    "UPDATED_BY" BIGINT,
    "BS" VARCHAR(255),
    "CATCH_PHRASE" VARCHAR(255),
    "NAME" VARCHAR(255)
);     
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMPANY; 
CREATE CACHED TABLE "PUBLIC"."FILE_STORE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F23B705D_2C1E_4F03_8257_C8F3576482D8" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F23B705D_2C1E_4F03_8257_C8F3576482D8",
    "FILE" BLOB,
    "FILE_IDENTITY" VARCHAR(255),
    "FILE_NAME" VARCHAR(255),
    "FILE_PATH" VARCHAR(255),
    "FILE_SIZE" BIGINT,
    "FILE_TYPE" VARCHAR(255),
    "FILEURI" VARCHAR(255),
    "ORIGINAL_FILE_NAME" VARCHAR(255)
);      
ALTER TABLE "PUBLIC"."FILE_STORE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FILE_STORE;              
CREATE CACHED TABLE "PUBLIC"."GEO"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_73AB6AAD_7CDC_46FB_B2CD_651335C72558" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_73AB6AAD_7CDC_46FB_B2CD_651335C72558",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "CREATED_BY" BIGINT,
    "UPDATED_BY" BIGINT,
    "LAT" VARCHAR(255),
    "LNG" VARCHAR(255)
);           
ALTER TABLE "PUBLIC"."GEO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_11" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GEO;     
CREATE CACHED TABLE "PUBLIC"."ORDER_PRODUCT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D2BA9875_601F_4AC6_BBDC_BB67671D92E1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D2BA9875_601F_4AC6_BBDC_BB67671D92E1",
    "PRODUCT_ID" BIGINT,
    "PRODUCT_QUANTITY" DOUBLE,
    "ODER_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_PRODUCT;           
CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F2B87DB0_606B_4D40_B735_BF4719D02ADC" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F2B87DB0_606B_4D40_B735_BF4719D02ADC",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "CREATED_BY" BIGINT,
    "UPDATED_BY" BIGINT,
    "PROD_DESC" VARCHAR(1000),
    "PROD_MODEL" VARCHAR(40),
    "PROD_NAME" VARCHAR(40),
    "PROD_PRICE" DOUBLE NOT NULL,
    "PROD_QUANTITY" DOUBLE NOT NULL,
    "PROD_SKU" VARCHAR(40),
    "PROD_SPL_PRICE" DOUBLE NOT NULL,
    "PROD_TAGS" VARCHAR(500),
    "CATEGORY_ID" BIGINT,
    "USER_ID" BIGINT
);              
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT; 
CREATE CACHED TABLE "PUBLIC"."PRODUCT_ATTRIBUTE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_651F689F_E715_4FA5_B53C_E0650249EE23" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_651F689F_E715_4FA5_B53C_E0650249EE23",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "NAME" VARCHAR(255),
    "VALUE" VARCHAR(255),
    "PRODUCT_ID" BIGINT
);    
ALTER TABLE "PUBLIC"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_ATTRIBUTE;       
CREATE CACHED TABLE "PUBLIC"."PRODUCT_PHOTO"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_850E4BB3_4F5D_4DB4_9D86_B749061EF912" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_850E4BB3_4F5D_4DB4_9D86_B749061EF912",
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "THUMBNAIL_URL" VARCHAR(255),
    "TITLE" VARCHAR(255),
    "URL" VARCHAR(255),
    "PRODUCT_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."PRODUCT_PHOTO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_42" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_PHOTO;           
CREATE CACHED TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_218B2E7D_4BBF_46E3_B380_38D9B76BCEDF" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_218B2E7D_4BBF_46E3_B380_38D9B76BCEDF",
    "NAME" VARCHAR(255)
);  
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;    
INSERT INTO "PUBLIC"."ROLE" VALUES
(1, 'ROLE_ADMIN'),
(2, 'ROLE_USER'),
(3, 'ROLE_VENDOR');
CREATE CACHED TABLE "PUBLIC"."USER_ROLE"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);  
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;               
INSERT INTO "PUBLIC"."USER_ROLE" VALUES
(1, 2),
(1, 1),
(1, 3);            
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."UKSPSNWR241E9K9C8P5XL4K45IH" UNIQUE("USERNAME");    
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."UK4VJ92UX8A2EEHDS1MDVMKS473" UNIQUE("EMAIL");       
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."UK_EPK9IM9L9Q67XMWI4HBED25DO" UNIQUE("NAME");            
ALTER TABLE "PUBLIC"."USER_ROLE" ADD CONSTRAINT "PUBLIC"."FKNNJWIN2R8OAJS3WMC8SBN0672" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."FKGUVVXRCTBDV18JGVU6P2E5K7H" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FKGLQ4B37AOTOBXF4II7FOOI0PI" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."APP_ORDER" ADD CONSTRAINT "PUBLIC"."FK3L511F5XKA0LH6HUQ64I14OXU" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."FKGYBWIIEYFCNX5AN03YGGWVAIL" FOREIGN KEY("COMPANY_ID") REFERENCES "PUBLIC"."COMPANY"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."FKR8NVG1P650UNXV06FPA50DXK9" FOREIGN KEY("ADDRESS_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKI056J0CK0MTOVA9RQ2PQQRPXV" FOREIGN KEY("ODER_ID") REFERENCES "PUBLIC"."APP_ORDER"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."PRODUCT_ATTRIBUTE" ADD CONSTRAINT "PUBLIC"."FKLEFS59Y5KMSBU017N1WP10GF2" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."CART_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKLV5X4IRESNV4XSPVOMRWD8EJ9" FOREIGN KEY("CART_ID") REFERENCES "PUBLIC"."CART"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."CART" ADD CONSTRAINT "PUBLIC"."FKHRKJ9G6RMOPUQENCU25CJXA53" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FK1MTSBUR82FRN64DE7BALYMQ9S" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."PRODUCT_PHOTO" ADD CONSTRAINT "PUBLIC"."FKSGI4KRGB65FKTQ55A5XW6SEQQ" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."FKCO48E3Q5MLQ831IJYSSN2T25Q" FOREIGN KEY("GEO_ID") REFERENCES "PUBLIC"."GEO"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."USER_ROLE" ADD CONSTRAINT "PUBLIC"."FKA68196081FVOVJHKEK5M97N3Y" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;       
